# configs/sample_mvp.yml
# Outlier Detection – MVP batch configuration (R-first)

datasets:
  - name: customers_aug
    input:
      path: data/customers_aug.csv
    schema:
      id_cols: [customer_id]
      numeric_cols: [monthly_spend, visits_30d]
      categorical_cols: [plan_type, region]
      time_col: signup_date
    # Optional per-dataset overrides (inherit from global run.detectors if omitted)
    # run:
    #   detectors:
    #     iqr: { enabled: true, whisker_k: 1.5 }

  - name: web_traffic
    input:
      path: data/web_traffic.csv
    schema:
      id_cols: [page_id]
      numeric_cols: [sessions, bounce_rate]
      categorical_cols: []
      time_col: date

run:
  detectors:
    # --- Univariate ---
    iqr: { enabled: true, whisker_k: 1.5 }          # increase to 3.0 to be more conservative
    mad: { enabled: true, z_thresh: 3.5 }           # lower to 3.0/2.5 to increase sensitivity

    # --- Multivariate ---
    isolation_forest:
      enabled: true
      contamination: 0.03                           # 1–3% typical in production
      ntrees: 200
      sample_size: 256
    lof:
      enabled: true
      minPts: 10

    # --- Time Series (requires time_col in schema) ---
    tsoutliers: { enabled: true }                   # ARIMA-style outliers; auto-noop if pkg missing
    anomalize:  { enabled: true, method: stl, alpha: 0.05 }  # decomposition-based anomalies
    fable:      { enabled: false }                  # set true if tsibble/fable installed

controls:
  max_flagged_pct: 10        # cap total flagged rows as % of dataset size
  min_support_rows: 2        # require ≥ this many flags per column after merge to retain it
  suppressions:
    - dataset: web_traffic
      window: { start: 2024-12-24, end: 2024-12-26 }  # ignore predictable holiday spikes
  whitelist:
    columns: []
    value_ranges: []

reporting:
  formats: [md, csv, html]   # html requires rmarkdown; summary.md is always written
  out_dir_root: reports

backfeed:
  emit_rule_candidates: true
  out_dir_root: artifacts
