# Outlier Detection – MVP Batch Config
# Place at: configs/sample_mvp.yml

# You can list one or many datasets. Each gets its own report/artifact folder.
datasets:
  - name: customers_aug
    input:
      path: data/customers_aug.csv
    schema:
      id_cols: [customer_id]
      numeric_cols: [monthly_spend, visits_30d]
      categorical_cols: [plan_type, region]
      time_col: signup_date

  - name: web_traffic
    input:
      path: data/web_traffic.csv
    schema:
      id_cols: [page_id]
      numeric_cols: [sessions, bounce_rate]
      categorical_cols: []
      time_col: date

run:
  detectors:
    # Univariate
    iqr: { enabled: true, whisker_k: 2.0 }
    mad: { enabled: true, z_thresh: 3.5 }

    # Multivariate
    isolation_forest:
      enabled: true
      contamination: 0.02       # target outlier fraction
      ntrees: 200               # isotree trees
      sample_size: 256          # subsampling size
    lof:
      enabled: true
      minPts: max(10, round(0.02 * n_rows))                # neighborhood size for LOF

    # Time series (MVP + Hyndman ecosystem)
    tsoutliers: { enabled: true }
    anomalize:
      enabled: true
      method: stl               # stl | twitter
      alpha: 0.05

  parallel: 1                   # increase for parallel runs later

controls:
  max_flagged_pct: 10
  min_support_rows: 2
  suppressions:
    - dataset: web_traffic
      window: { start: 2024-12-24, end: 2024-12-26 }  # ignore holidays
  whitelist:
    columns: []
    value_ranges: []

reporting:
  formats: [md, csv, html]      # html requires rmarkdown wired in reporting.R
  out_dir_root: reports

backfeed:
  emit_rule_candidates: true
  out_dir_root: artifacts
